export const sidebarLinks = [
  {
    id: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: "LayoutDashboard",
  },
  {
    id: "Members",
    label: "Membership",
    path: "/dashboard/members",
    icon: "Users",
  },
  // {
  //   id: "bookings",
  //   label: "Bookings",
  //   path: "/dashboard/bookings",
  //   icon: "CalendarCheck2",
  // },
  // {
  //   id: "sessions",
  //   label: "Sessions",
  //   path: "/dashboard/sessions",
  //   icon: "Clock3",
  // },
  // {
  //   id: "coaches",
  //   label: "Coaches",
  //   path: "/dashboard/coaches",
  //   icon: "UserSquare2",
  // },
  // {
  //   id: "facilities",
  //   label: "Facilities",
  //   path: "/dashboard/facilities",
  //   icon: "Building2",
  // },
  {
    id: "swimming-pool",
    label: "Swimming Pool",
    path: "/dashboard/swimming-pool",
    icon: "Waves",
  },
  {
    id: "basketball",
    label: "Basketball",
    path: "/dashboard/basketball",
    icon: "Dribbble",
  },
  {
    id: "pickleball",
    label: "Pickleball",
    path: "/dashboard/pickleball",
    icon: "CircleDot",
  },
  { id: "cricket", label: "Cricket", path: "/dashboard/cricket", icon: "Zap" },
  {
    id: "skating",
    label: "Skating",
    path: "/dashboard/skating",
    icon: "Footprints",
  },
  {
    id: "calendar",
    label: "Calendar Booking",
    path: "/dashboard/calendar",
    icon: "CalendarDays",
  },
  {
    id: "pricing",
    label: "Products & Pricing",
    path: "/dashboard/pricing",
    icon: "Tags",
  },
  {
    id: "ledger",
    label: "Advance Ledger",
    path: "/dashboard/ledger",
    icon: "BookOpen",
  },
  {
    id: "reports",
    label: "Reports",
    path: "/dashboard/reports",
    icon: "BarChart3",
  },
  {
    id: "settings",
    label: "Settings",
    path: "/dashboard/settings",
    icon: "Settings",
  },
];
